version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/box-frontend"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "npm"
    directory: "/box-worker"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "worker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"