// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetBrandsData, GetBrandsResponses, GetCategoriesData, GetCategoriesResponses, GetImagesData, GetProductsByIdData, GetProductsByIdErrors, GetProductsByIdResponses, GetProductsData, GetProductsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all products with optional filtering by brand, category, or minimum rating
 */
export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<GetProductsData, ThrowOnError>) => (options?.client ?? client).get<GetProductsResponses, unknown, ThrowOnError>({ url: '/products/', ...options });

/**
 * Get a specific product by its ID (slug format)
 */
export const getProductsById = <ThrowOnError extends boolean = false>(options: Options<GetProductsByIdData, ThrowOnError>) => (options.client ?? client).get<GetProductsByIdResponses, GetProductsByIdErrors, ThrowOnError>({ url: '/products/{id}', ...options });

/**
 * List all brands ordered by name
 */
export const getBrands = <ThrowOnError extends boolean = false>(options?: Options<GetBrandsData, ThrowOnError>) => (options?.client ?? client).get<GetBrandsResponses, unknown, ThrowOnError>({ url: '/brands/', ...options });

/**
 * List all valid product categories
 */
export const getCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetCategoriesResponses, unknown, ThrowOnError>({ url: '/categories', ...options });

/**
 * Serve an image from R2 storage (supports nested paths like products/image.png)
 */
export const getImages = <ThrowOnError extends boolean = false>(options: Options<GetImagesData, ThrowOnError>) => (options.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/images/*', ...options });
