// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        brand?: string;
        category?: string;
        minRating?: string;
    };
    url: '/products/';
};

export type GetProductsResponses = {
    /**
     * Response for status 200
     */
    200: {
        products: Array<{
            id: string;
            name: string;
            brand: string;
            category: string;
            rating: number;
            comment: string | null;
            imageUrl: string | null;
        }>;
    };
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type GetProductsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type GetProductsByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetProductsByIdError = GetProductsByIdErrors[keyof GetProductsByIdErrors];

export type GetProductsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        brand: string;
        category: string;
        rating: number;
        comment: string | null;
        imageUrl: string | null;
    };
};

export type GetProductsByIdResponse = GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type GetBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/brands/';
};

export type GetBrandsResponses = {
    /**
     * Response for status 200
     */
    200: {
        brands: Array<{
            id: string;
            name: string;
        }>;
    };
};

export type GetBrandsResponse = GetBrandsResponses[keyof GetBrandsResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type GetCategoriesResponses = {
    /**
     * Response for status 200
     */
    200: {
        categories: Array<string>;
        count: number;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetImagesData = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/images/*';
};
