// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        brand?: string;
        category?: string;
        minRating?: string;
    };
    url: '/products/';
};

export type GetProductsResponses = {
    /**
     * Response for status 200
     */
    200: {
        products: Array<{
            id: string;
            name: string;
            brand: string;
            category: string;
            rating: number;
            comment: string | null;
            imageUrl: string | null;
        }>;
    };
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type PostProductsData = {
    body: {
        name: string;
        brand: string;
        category: 'food' | 'snack' | 'ice-cream' | 'drink' | 'fragrance' | 'personal-care' | 'beauty' | 'household' | 'electronics' | 'other';
        rating: number;
        comment?: string;
        /**
         * Base64-encoded image data URL (e.g., data:image/png;base64,...)
         */
        imageBase64?: string;
    };
    path?: never;
    query?: never;
    url: '/products/';
};

export type PostProductsErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: string;
    };
    /**
     * Response for status 409
     */
    409: {
        error: string;
        existingId?: string;
    };
};

export type PostProductsError = PostProductsErrors[keyof PostProductsErrors];

export type PostProductsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        name: string;
        brand: string;
        category: string;
        rating: number;
        comment: string | null;
        imageUrl: string | null;
    };
};

export type PostProductsResponse = PostProductsResponses[keyof PostProductsResponses];

export type DeleteProductsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type DeleteProductsByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type DeleteProductsByIdError = DeleteProductsByIdErrors[keyof DeleteProductsByIdErrors];

export type DeleteProductsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        message: string;
        deleted: {
            id: string;
            name: string;
            brand: string;
            category: string;
            rating: number;
            comment: string | null;
            imageUrl: string | null;
        };
    };
};

export type DeleteProductsByIdResponse = DeleteProductsByIdResponses[keyof DeleteProductsByIdResponses];

export type GetProductsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type GetProductsByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetProductsByIdError = GetProductsByIdErrors[keyof GetProductsByIdErrors];

export type GetProductsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        brand: string;
        category: string;
        rating: number;
        comment: string | null;
        imageUrl: string | null;
    };
};

export type GetProductsByIdResponse = GetProductsByIdResponses[keyof GetProductsByIdResponses];

export type PutProductsByIdData = {
    body: {
        name?: string;
        brand?: string;
        category?: 'food' | 'snack' | 'ice-cream' | 'drink' | 'fragrance' | 'personal-care' | 'beauty' | 'household' | 'electronics' | 'other';
        rating?: number;
        comment?: string;
        /**
         * Base64-encoded image data URL (e.g., data:image/png;base64,...)
         */
        imageBase64?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type PutProductsByIdErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type PutProductsByIdError = PutProductsByIdErrors[keyof PutProductsByIdErrors];

export type PutProductsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        brand: string;
        category: string;
        rating: number;
        comment: string | null;
        imageUrl: string | null;
    };
};

export type PutProductsByIdResponse = PutProductsByIdResponses[keyof PutProductsByIdResponses];

export type GetBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/brands/';
};

export type GetBrandsResponses = {
    /**
     * Response for status 200
     */
    200: {
        brands: Array<{
            id: string;
            name: string;
        }>;
    };
};

export type GetBrandsResponse = GetBrandsResponses[keyof GetBrandsResponses];

export type PostBrandsData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/brands/';
};

export type PostBrandsErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: string;
    };
    /**
     * Response for status 409
     */
    409: {
        error: string;
        existingId?: string;
    };
};

export type PostBrandsError = PostBrandsErrors[keyof PostBrandsErrors];

export type PostBrandsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        name: string;
    };
};

export type PostBrandsResponse = PostBrandsResponses[keyof PostBrandsResponses];

export type DeleteBrandsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/brands/{id}';
};

export type DeleteBrandsByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 409
     */
    409: {
        error: string;
        productCount?: number;
    };
};

export type DeleteBrandsByIdError = DeleteBrandsByIdErrors[keyof DeleteBrandsByIdErrors];

export type DeleteBrandsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        message: string;
        deleted: {
            id: string;
            name: string;
        };
    };
};

export type DeleteBrandsByIdResponse = DeleteBrandsByIdResponses[keyof DeleteBrandsByIdResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type GetCategoriesResponses = {
    /**
     * Response for status 200
     */
    200: {
        categories: Array<string>;
        count: number;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetImagesByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/images/{key}';
};
