// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getBrands, getCategories, getImages, getProducts, getProductsById, type Options } from '../sdk.gen';
import type { GetBrandsData, GetBrandsResponse, GetCategoriesData, GetCategoriesResponse, GetImagesData, GetProductsByIdData, GetProductsByIdError, GetProductsByIdResponse, GetProductsData, GetProductsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProductsQueryKey = (options?: Options<GetProductsData>) => createQueryKey('getProducts', options);

/**
 * List all products with optional filtering by brand, category, or minimum rating
 */
export const getProductsOptions = (options?: Options<GetProductsData>) => queryOptions<GetProductsResponse, DefaultError, GetProductsResponse, ReturnType<typeof getProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsQueryKey(options)
});

export const getProductsByIdQueryKey = (options: Options<GetProductsByIdData>) => createQueryKey('getProductsById', options);

/**
 * Get a specific product by its ID (slug format)
 */
export const getProductsByIdOptions = (options: Options<GetProductsByIdData>) => queryOptions<GetProductsByIdResponse, GetProductsByIdError, GetProductsByIdResponse, ReturnType<typeof getProductsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProductsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsByIdQueryKey(options)
});

export const getBrandsQueryKey = (options?: Options<GetBrandsData>) => createQueryKey('getBrands', options);

/**
 * List all brands ordered by name
 */
export const getBrandsOptions = (options?: Options<GetBrandsData>) => queryOptions<GetBrandsResponse, DefaultError, GetBrandsResponse, ReturnType<typeof getBrandsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBrands({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBrandsQueryKey(options)
});

export const getCategoriesQueryKey = (options?: Options<GetCategoriesData>) => createQueryKey('getCategories', options);

/**
 * List all valid product categories
 */
export const getCategoriesOptions = (options?: Options<GetCategoriesData>) => queryOptions<GetCategoriesResponse, DefaultError, GetCategoriesResponse, ReturnType<typeof getCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCategoriesQueryKey(options)
});

export const getImagesQueryKey = (options: Options<GetImagesData>) => createQueryKey('getImages', options);

/**
 * Serve an image from R2 storage (supports nested paths like products/image.png)
 */
export const getImagesOptions = (options: Options<GetImagesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getImagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getImages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getImagesQueryKey(options)
});
