// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteBrandsById, deleteProductsById, getBrands, getCategories, getImages, getProducts, getProductsById, type Options, postBrands, postProducts, putProductsById } from '../sdk.gen';
import type { DeleteBrandsByIdData, DeleteBrandsByIdError, DeleteBrandsByIdResponse, DeleteProductsByIdData, DeleteProductsByIdError, DeleteProductsByIdResponse, GetBrandsData, GetBrandsResponse, GetCategoriesData, GetCategoriesResponse, GetImagesData, GetProductsByIdData, GetProductsByIdError, GetProductsByIdResponse, GetProductsData, GetProductsResponse, PostBrandsData, PostBrandsError, PostBrandsResponse, PostProductsData, PostProductsError, PostProductsResponse, PutProductsByIdData, PutProductsByIdError, PutProductsByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProductsQueryKey = (options?: Options<GetProductsData>) => createQueryKey('getProducts', options);

/**
 * List all products with optional filtering by brand, category, or minimum rating
 */
export const getProductsOptions = (options?: Options<GetProductsData>) => queryOptions<GetProductsResponse, DefaultError, GetProductsResponse, ReturnType<typeof getProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsQueryKey(options)
});

/**
 * Create a new product with name, brand, category, rating, and optional comment/image. Send image as base64 data URL in imageBase64 field. The ID is automatically generated as a ULID.
 */
export const postProductsMutation = (options?: Partial<Options<PostProductsData>>): UseMutationOptions<PostProductsResponse, PostProductsError, Options<PostProductsData>> => {
    const mutationOptions: UseMutationOptions<PostProductsResponse, PostProductsError, Options<PostProductsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postProducts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a product by its ID
 */
export const deleteProductsByIdMutation = (options?: Partial<Options<DeleteProductsByIdData>>): UseMutationOptions<DeleteProductsByIdResponse, DeleteProductsByIdError, Options<DeleteProductsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteProductsByIdResponse, DeleteProductsByIdError, Options<DeleteProductsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteProductsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProductsByIdQueryKey = (options: Options<GetProductsByIdData>) => createQueryKey('getProductsById', options);

/**
 * Get a specific product by its ID (slug format)
 */
export const getProductsByIdOptions = (options: Options<GetProductsByIdData>) => queryOptions<GetProductsByIdResponse, GetProductsByIdError, GetProductsByIdResponse, ReturnType<typeof getProductsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProductsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsByIdQueryKey(options)
});

/**
 * Update an existing product by ID with partial data. Send image as base64 data URL in imageBase64 field.
 */
export const putProductsByIdMutation = (options?: Partial<Options<PutProductsByIdData>>): UseMutationOptions<PutProductsByIdResponse, PutProductsByIdError, Options<PutProductsByIdData>> => {
    const mutationOptions: UseMutationOptions<PutProductsByIdResponse, PutProductsByIdError, Options<PutProductsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putProductsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBrandsQueryKey = (options?: Options<GetBrandsData>) => createQueryKey('getBrands', options);

/**
 * List all brands ordered by name
 */
export const getBrandsOptions = (options?: Options<GetBrandsData>) => queryOptions<GetBrandsResponse, DefaultError, GetBrandsResponse, ReturnType<typeof getBrandsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBrands({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBrandsQueryKey(options)
});

/**
 * Create a new brand with a name. The ID is automatically generated as a ULID.
 */
export const postBrandsMutation = (options?: Partial<Options<PostBrandsData>>): UseMutationOptions<PostBrandsResponse, PostBrandsError, Options<PostBrandsData>> => {
    const mutationOptions: UseMutationOptions<PostBrandsResponse, PostBrandsError, Options<PostBrandsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBrands({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a brand by its ID. Cannot delete brands with associated products.
 */
export const deleteBrandsByIdMutation = (options?: Partial<Options<DeleteBrandsByIdData>>): UseMutationOptions<DeleteBrandsByIdResponse, DeleteBrandsByIdError, Options<DeleteBrandsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteBrandsByIdResponse, DeleteBrandsByIdError, Options<DeleteBrandsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteBrandsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCategoriesQueryKey = (options?: Options<GetCategoriesData>) => createQueryKey('getCategories', options);

/**
 * List all valid product categories
 */
export const getCategoriesOptions = (options?: Options<GetCategoriesData>) => queryOptions<GetCategoriesResponse, DefaultError, GetCategoriesResponse, ReturnType<typeof getCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCategoriesQueryKey(options)
});

export const getImagesQueryKey = (options: Options<GetImagesData>) => createQueryKey('getImages', options);

/**
 * Serve an image from R2 storage (supports nested paths like products/image.png)
 */
export const getImagesOptions = (options: Options<GetImagesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getImagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getImages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getImagesQueryKey(options)
});
